### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by 75lb** [75lb/renamer#13]
- [ ] accept input from stdin
- [ ] make more hackable, more easy to insert additional functions into pipeline.. .use(middleware) type approach?
- [ ] maintain a history so we can view and re-run previous renames
- [ ] `--js` expression and `{{js}}` token. e.g.: 
```sh
$ renamer -f file -r 'file{{js}}' --js Date.now() * 
$ renamer -f file -r '{{js}}-file' --js process.cwd() * 
$ renamer -r '{{js}}.txt' --js sprintf("%10s", index) * 
# 0000000001.txt
# 0000000002.txt
# etc

$ renamer -r '{{index}} ({{js}}).txt' --js moment(new Date()).fromNow() * 
# 1 (1 Day ago).txt
# 2 (4 Months ago).txt

$ renamer -f '(\w+) -r '{{js}}' --js '$1.toTitleCase()' * 
# filename.txt -> Filename.txt
```
- [ ] Presets

instead of passing the same CLI args everytime, e.g. 

    $ renamer --find this --replace that *

i want to create a preset, like 

    $ renamer --find this --replace that * --name renameThisWithThat 

and to use it: 

    $ renamer --preset renameThisWithThat  *
- [ ] sign and share presets
